name 'lyrisdemo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures lyrisdemo'
long_description 'Installs/Configures lyrisdemo'
version '0.1.0'

depends 'java'
depends 'maven'
depends 'firewall'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.17'
depends 'database', '~> 4.0.3'