name 'lyrisdemo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures lyrisdemo'
long_description 'Installs/Configures lyrisdemo'
version '0.1.0'

depends 'java'
depends 'maven'
depends 'firewall'